---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytuesdayR)
library(extrafont) # for adding google font
library(ggrough)
library(patchwork)
library(rbokeh)
```

```{r}
tt <- tt_load("2021-01-26")
d <- tt$plastics
```


```{r}
loadfonts()

font <- fonts()[112]

theme_set(theme_minimal(base_family = font))
```


#glimpse
```{r}
d %>% head() %>% glimpse()
```

```{r}
vol <- d %>% 
  count(year, wt = volunteers)

type <- d %>% 
  pivot_longer(cols = hdpe:pvc, 
               names_to = "type", 
             values_to = "qt") %>% 
  count(year, type, wt = qt)
  
```


```{r}
p1 <- vol %>% 
  ggplot(aes(x = as.factor(year), y = n))+
  scale_y_continuous(labels = scales::number_format())+
  geom_col(aes(fill = as.factor(year)))+
#  theme_minimal()+
  theme(legend.position = "none")+
  labs(title = "Title",
        subtitle = "sub",
        y = "",
        x = "")
```   


```{r}
p2 <- type %>% 
  ggplot(aes(x = type, y =n, 
             fill = as.factor(year), color = as.factor(year) ))+
  geom_col(position = "dodge", width = .75)+
  scale_y_continuous(labels = scales::number_format())+
# theme_minimal()+
  theme(legend.position = "none")+
  labs(title = "Title",
        subtitle = "sub",
        y = "",
        x = "")
```

```{r}
unique(type$type) 

labels <- paste0(unique(type$type)[1]," - " ,"High density polyethylene count (Plastic milk containers, plastic bags, bottle caps, trash cans, oil cans, plastic lumber, toolboxes, supplement containers)\n\n",
       unique(type$type)[2], " - ", "Low density polyethylene count (Plastic bags, Ziploc bags, buckets, squeeze bottles, plastic tubes, chopping boards)\n\n",
       unique(type$type)[3], " - ", "Category marked other count\n\n",
       unique(type$type)[4], " - ", "Polyester plastic count (Polyester fibers, soft drink bottles, food containers (also see plastic bottles)\n\n",
       unique(type$type)[5], " - ", "Polypropylene count (Flower pots, bumpers, car interior trim, industrial fibers, carry-out beverage cups, microwavable food containers, DVD keep cases)\n\n",
       unique(type$type)[6], " - ", "Polystyrene count (Toys, video cassettes, ashtrays, trunks, beverage/food coolers, beer cups, wine and champagne cups, carry-out food containers, Styrofoam)\n\n",
       unique(type$type)[7], " - ", "PVC plastic count (Window frames, bottles for chemicals, flooring, plumbing pipes)")

p <- ggplot()+
  geom_blank()+
  annotate(geom = "text", label = labels,
            
            x = 1,
            xmax = 1.5,
#            xmax = 1,
            y = .5,
            hjust = 0)+
  theme(axis.text = element_blank(),
        panel.grid = element_blank())+
  labs(title = "",
        subtitle = "",
        y = "",
        x = "")
```



```{r}
p3 <- p1 + p2

options <- list(
  Background=list(roughness=8),
  GeomCol=list(fill_style="zigzag", angle_noise=0.5, fill_weight=2))

pdf("saveteste.pdf")
ggrough::get_rough_chart(p3, options, family = "Homemade Apple", font_size_booster = 1.45)
dev.off()
```


```{r}
ggrough::get_rough_chart(s, options)
```

```{r}
par(mfrow=c(1,2))
```

```{r}
s <- (p1 + p) / p2

t1
t2
```


```{r}
grid::grob(t2)

library(webshot)

webshot::webshot(t2, file = "teste.png")



library(plotly)

subplot(t1, t2)

export(t2, file = "image3.png")

png("save.png")
t2
dev.off()
```

```{r}
library(htmlwidgets)

saveWidget(t2, "rough_chart.html")
webshot(url = "rough_chart.html" , file = "output4.png")



```

