---
title: "TidyTemplate"
date: 2021-03-21
output: html_output
---

# Libraries
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(patchwork)
library(ggshadow)
library(ggdark)
library(extrafont)
library(scales)
```

# Load
```{r Load}
tt <- tt_load("2021-03-16")
```

# Initial Sets
```{r Readme, eval = interactive()}
setwd("C:/r_files/tidytuesday2021/codes/week_12")

tt

cap.source <- "Source: SteamCharts"

loadfonts()

options(scipen = 999)
```

# Manipulating
```{r Wrangle}
dt <- tt$games

dt %>% glimpse()

# Manipulação 1
dt <- dt %>% 
  mutate(year = as.integer(year)) %>% 
  drop_na() %>% 
  mutate(month = fct_relevel(month, month.name)) %>% 
  filter(year < 2021)

# Manipulaçaõ 2 
dt.2 <- dt %>% 
  group_by(gamename) %>% 
  mutate(top.gamename = sum(avg)) %>% 
  ungroup() %>% 
  mutate(gamename = fct_lump(gamename, 10, w = top.gamename),
         gamename = fct_reorder(gamename, top.gamename, .desc = T))

# Manipulação 3 - Mèdia dos ganhos e perdas 
dt.3 <- dt.2 %>% 
  group_by(month, year) %>% 
  mutate(mean = mean(gain)) %>% 
  select(gamename, year, month, avg, gain, mean) %>%
  mutate(size = round(gain/10000, 0)) %>% 
  filter(gamename != "Other") %>% 
  filter(year > 2012)

dt.3 <- dt.3 %>% 
  mutate(month.2 = str_sub(month, 1, 3))

```

# Plot 1
```{r}
dev.off()
windows(width = 12, height = 6)

(plot.1 <- dt.3 %>%
  ggplot(aes(x = month, y = mean))+
  geom_hline(yintercept = 0, color = "white", 
              linetype = "dashed", alpha = .5)+
  ggshadow::geom_glowline(group = 1, color = "#3BF007")+
  scale_x_discrete(label = month.abb
                   )+
  facet_wrap(vars(year), ncol = 4)+
  ggdark::dark_theme_minimal()+
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x = element_text(angle=90, vjust = 0.5),
        axis.title.x = element_text(hjust = 1),
        axis.title.y = element_text(hjust = 1),
        strip.text = element_text(hjust = 0, face = "bold"),
        plot.title.position = "plot",
        plot.margin = margin(.5,1,.5,1, "cm"))+
  labs(title = "Gamer Players - Average of gains and losses",
        subtitle = "By year and month"))
```

# Colors
```{r}
scales::show_col(colors)

color.1 <- paletteer::paletteer_d("ggsci::lanonc_lancet")
color.2 <- paletteer::paletteer_d("yarrr::xmen")

colors <- c( color.1, color.2)[c(1:7, 17:15)]
```

# Plot 2
```{r}
dev.off()
windows(width = 12, height = 6)

(plot.2 <- dt.3 %>%
  rename("Game" = gamename) %>%  
  ggplot(aes(x = month, y = avg, color = Game, alpha =.3))+
  scale_x_discrete(label = month.abb
                   )+
  ggshadow::geom_shadowpoint(aes(shadowcolour = Game,
                             shadowsize = 4), 
                             position = "jitter")+
  ggshadow::scale_shadowcolour_manual(values = colors) +
  scale_color_manual( values = colors)+
  scale_y_continuous(label = scales::label_number(big.mark = "."))+
  ggdark::dark_theme_minimal()+
  facet_wrap(vars(year), ncol = 4)+
  theme(legend.position = "top",
        legend.direction = "horizontal",
        legend.text = element_text(size = 8),
        #legend.key.width = unit(5, "cm"),
        legend.title.align = 1,
        axis.text.x = element_text(angle=90, vjust = 0.5),
        axis.title.x = element_text(hjust = 1),
        axis.title.y = element_text(hjust = 1),
        strip.text = element_text(hjust = 0, face = "bold"),
        plot.title.position = "plot",
        plot.margin = margin(.5,1,.5,1, "cm"),
        #panel.grid.major = element_line(color = "gray15"),
        #panel.
        #panel.grid.minor = element_line(color = "gray15"),
        #panel.background = element_rect(fill = "gray10"),
        #plot.background = element_rect(fill = "gray10")
        )+
  guides(alpha = FALSE,
         size = FALSE)+
  labs(title = "Average of players in the top 10 games",
       subtitle = "By games, month and year",
       caption = cap.source))
```


# Join plots
```{r}
final.plot <- plot.1/plot.2 + patchwork::plot_layout(heights = c(1, 1.3))

```

# Save
```{r}
ggsave("week_12.png",
    plot = final.plot,
    device = ragg::agg_png(width = 12, 
            height = 15, 
            units = "in", 
            res = 600))
```

