# https://www.blog.cultureofinsight.com/2017/09/animated-choropleth-maps-in-r/
```{r}
setwd("C:/rstats/tidytuesday/week_42")

pacman::p_load(tidytuesdayR, tidyverse, ggmap, gganimate, ggtext)
```

```{r}
tuesdata <- tidytuesdayR::tt_load('2021-10-12')

seafood <- tuesdata$`seafood-and-fish-production-thousand-tonnes`

windowsFonts(font = windowsFont("Baskerville Old Face"))

options(scipen = 999)
```

```{r}
seadfood <- seafood %>% janitor::clean_names() 

seadfood.b <- seadfood %>% 
  pivot_longer(cols = 4:10, names_to = "commodity", values_to = "value") %>%
  mutate(commodity = str_remove(commodity, "commodity_balances_livestock_and_fish_primary_equivalent_"),
         commodity = str_remove(commodity, "_production_5510_tonnes"),
         commodity = str_remove(commodity, "_\\d{4}")) 
```


```{r}
world <- map_data("world")

seadfood.c <- world %>% 
  mutate(region = recode(region, "UK" = "United Kingdom"),
         region = recode(region, "USA" = "United States")) %>% 
  #count(commodity);;
  #filter(commodity == "pelagic_fish") %>% 
  left_join(seadfood.b, by = c("region" = "entity")) 

sort(setdiff(world$region, seadfood.b$entity))
sort(setdiff(seadfood.b$entity, world$region))


seadfood.d <- seadfood.c %>%  
  mutate(commodity = str_replace(commodity, "_", " "),
        commodity = str_to_title(commodity),
        commodity = str_replace(commodity, "Other", "- Other")) %>% 
  mutate(commodity = fct_reorder(commodity, value, .fun = sum, na.rm = T, .desc = T)) %>% 
  filter(year == 2013) %>%
  drop_na(code) %>%
  mutate(value = replace_na(value, replace = 0)) 
```


```{r}
seadfood.d$commodity

plot <- seadfood.d %>% 
  ggplot(aes(long, lat, group = group, fill = value))+
  scale_fill_viridis_c(option = "C", 
                       breaks = seq(5000000, 25000000, 5000000),
                       label = scales::number_format() )+
  geom_polygon(color = alpha("white",.5))+
  theme_void()+
  facet_wrap(vars(commodity))+
  labs(title = "Seafood and fish production",
       fill = "Tonnes (2013)", caption = "Source: OurWorldinData.org")+
  theme(plot.title =  element_text(hjust = .8, vjust = -50, 
                                   family = "font", size = 40, 
                                   face = "bold", color = "#264653"),
        plot.caption = element_text(size = 12),
        legend.position = "bottom", legend.direction = "horizontal",
        strip.text = element_text(family = "font", 
                                  size = 20, 
                                  vjust = 1,
                                  color = "#264653"),
        plot.margin = margin(1,1,1,1, "cm"))+
  guides(fill = guide_legend(title.position="top",
                             title.theme = element_text(size = 15, 
                                                        hjust = .5),
                             title.hjust = .5,
                             nrow = 1,
                             label.position = "bottom"))
```


```{r}
dev.off()
ggsave(filename = "week_42.png", 
       plot = plot, 
       device = ragg::agg_png(
       width = 16, height = 9, units = "in"))
```

