---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytuesdayR)
library(mdthemes)
library(patchwork)
library(scales)
library(extrafont)
```


```{r}
tt <- tidytuesdayR::tt_load(last_tuesday())

dt <- tt$student_debt

loadfonts()
font <- fonts()[20]

```

```{r}
caption <- "Source: Urban Institute and the US Census"

theme_set(
  theme_minimal(base_family = "Arial Black")+
  theme(plot.title = element_text(color = "#43281c", size =20),
        plot.title.position = "panel",
        axis.text = element_text(color = "#43281c", size = 15),
        plot.background = element_rect(fill = "#ECF1EE", color = "#ECF1EE"),
        panel.background = element_rect(fill = "#ECF1EE", color = "#ECF1EE"),
#        aspect.ratio = 1/3,
        plot.margin = margin(t = 2, unit = "cm"),
        legend.position = "bottom",
        legend.key.width = unit(3,"cm"),
        legend.text = element_text(color = "#43281c")))
```


```{r}
plot.1 <- dt %>%
  mutate(label.dollar = dollar(loan_debt, prefix = "")) %>% 
  ggplot(aes(as.factor(year), race, fill = loan_debt),
         show.legend = F)+
  geom_tile(color = "#ECF1EE", size=.5)+
  geom_text(aes(label = label.dollar),
            size = 4, color = "white", fontface = "bold")+
  paletteer::scale_fill_paletteer_c("gameofthrones::martell",
                      limits = c(min(dt$loan_debt), 
                                 max(dt$loan_debt)),
                      labels = dollar_format(prefix = ""),
                      breaks = seq(2000, 14000, 2000))+
  guides(fill = guide_legend(title.position="top",
                             title.hjust = 0,
                             label.position = "bottom",
                             ncol = 7))+
  labs(title = "Average family student loan debt for aged 25-55",
        y = "",
        x = "",
        fill = "$")
```


```{r}
plot.2 <- dt %>%
  mutate(label.pct = round(loan_debt_pct, 2)) %>%
  ggplot(aes(as.factor(year), race, fill = loan_debt_pct),
         show.legend = F)+
  geom_tile(color = "#ECF1EE", size=.5)+
  geom_text(aes(label = label.pct),
            size = 4, color = "white", fontface = "bold")+
  paletteer::scale_fill_paletteer_c("gameofthrones::martell",
                      limits = c(min(dt$loan_debt_pct), 
                                 max(dt$loan_debt_pct)))+
  guides(fill = guide_legend(title.position="top",
                             title.hjust = 0,
                             label.position = "bottom",
                             ncol = 5))+
  labs(title = "Share of families with student loan debt",
        y = "",
        x = "",
        fill = "%")
```

```{r}
plot.3 <- plot.1/plot.2+
  plot_annotation(
    title = "Students debt",
    caption = caption,
    theme = theme(
      plot.title = element_text(size = 22),
      plot.caption = element_text(size = 12, color = "#43281c"),
      plot.margin = margin(t = 1.5, r =1, l = 1, b = 1, unit = "cm")))
```

```{r}
ggsave("week_07.png",
    plot = plot.3,
    device = ragg::agg_png(width = 12, 
            height = 12, 
            units = "in", 
            res = 500))
dev.off()
```

